### ISSUE TITLE
Can this be used in Linux OS or WSL ?

### ISSUE THREAD

**Issue by meicale** [the-nix-way/nome#5]
This is quite great repo which has lots of helpful setting. I encounter problem when using it directly on WSL Ubuntu system. Its complains that
"
$ nix build "github:the-nix-way/nome#homeConfigurations.lucperkins.activationPackage"
error: flake 'github:the-nix-way/nome' does not provide attribute 'packages.x86_64-linux.homeConfigurations.lucperkins.activationPackage', 'legacyPackages.x86_64-linux.homeConfigurations.lucperkins.activationPackage' or 'homeConfigurations.lucperkins.activationPackage'
"
I guess the flake.nix doesn't set any x86_64-linux related system information. Would you mind expend this to flake to support it? Thank you so much.

**Comment by lucperkins** [comment]
@meicale This is meant only as my personal config, and I only use macOS for my daily work and hacking. You're free to use the code here however you like, however it's not intended to be used by others.
