### ISSUE TITLE
Cannot update flake (uuidv7)

### ISSUE THREAD

**Issue by gnuion** [the-nix-way/nome#6]
## Issue
When trying to update the flake with `nix flake update`, I get the error bellow. I checked for the repository of uuidv7 and could not find it.

```
warning: could not update cached head 'master' for 'ssh://git@github.com/DeterminateSystems/uuidv7.git'
error:
       … while updating the lock file of flake .../nome'
       … while updating the flake input 'uuidv7'
       … while fetching the input 'git+ssh://git@github.com/DeterminateSystems/uuidv7.git'
```

**Comment by lucperkins** [comment]
@gnuion That is actually a private flake and so it's to be expected that people outside of my org wouldn't be able to access it. In general, this isn't really meant to be used by anyone but me, so I'd recommend removing that input if you're using this project as a starter.
